//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp.UnitTypes
{
	public class Fighter: Unit
	{
		public Fighter(){
			this.MAX_HP = 20;
			this.STRENGTH = 10;
			this.VARIATION = 5;
			this.SPEED = 5;
			this.RANGE = 1;
		}

		protected override GameObject CreateModel(){
			var cube = GameObject.CreatePrimitive (PrimitiveType.Cube);
			cube.transform.position = new Vector3(0, 0.5f, 0);
			return cube;
		}

	}
}

