//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp.UnitTypes
{
    public class Shooter : Unit
    {
        public Shooter()
        {
            this.MAX_HP = 10;
            this.STRENGTH = 5;
            this.VARIATION = 2;
            this.SPEED = 2;
            this.RANGE = 3;
        }

        protected override GameObject CreateModel()
        {
            var cube = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            cube.name = "Unit Model";
            cube.transform.position = new Vector3(0, 0.5f, 0);
            return cube;
        }

    }
}

